0,29,org.assertj.core.error.future.ShouldHaveFailed_create_Test:should_create_error_message
1,29,org.assertj.core.error.future.ShouldHaveFailed_create_Test:should_create_error_message
2,29,org.assertj.core.error.future.ShouldHaveFailed_create_Test:should_create_error_message
0,29,org.assertj.core.internal.intarrays.IntArrays_assertContainsOnly_Test:should_pass_if_actual_contains_given_values_only_even_if_duplicated
1,29,org.assertj.core.internal.intarrays.IntArrays_assertContainsOnly_Test:should_pass_if_actual_contains_given_values_only_even_if_duplicated
2,29,org.assertj.core.internal.intarrays.IntArrays_assertContainsOnly_Test:should_pass_if_actual_contains_given_values_only_even_if_duplicated
0,29,org.assertj.core.api.SoftAssertionsTest:should_be_able_to_catch_exceptions_thrown_by_all_proxied_methods
1,29,org.assertj.core.api.SoftAssertionsTest:should_be_able_to_catch_exceptions_thrown_by_all_proxied_methods
2,29,org.assertj.core.api.SoftAssertionsTest:should_be_able_to_catch_exceptions_thrown_by_all_proxied_methods
0,29,org.assertj.core.api.SoftAssertionsTest:should_return_failure_after_fail
1,29,org.assertj.core.api.SoftAssertionsTest:should_return_failure_after_fail
2,29,org.assertj.core.api.SoftAssertionsTest:should_return_failure_after_fail
0,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailed_Test:should_fail_if_completable_future_was_cancelled
1,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailed_Test:should_fail_if_completable_future_was_cancelled
2,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailed_Test:should_fail_if_completable_future_was_cancelled
0,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailed_Test:should_fail_when_completable_future_is_null
1,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailed_Test:should_fail_when_completable_future_is_null
2,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailed_Test:should_fail_when_completable_future_is_null
0,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailed_Test:should_fail_if_completable_future_is_completed
1,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailed_Test:should_fail_if_completable_future_is_completed
2,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailed_Test:should_fail_if_completable_future_is_completed
0,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailed_Test:should_pass_if_completable_future_has_failed
1,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailed_Test:should_pass_if_completable_future_has_failed
2,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailed_Test:should_pass_if_completable_future_has_failed
0,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailed_Test:should_fail_if_completable_future_is_incomplete
1,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailed_Test:should_fail_if_completable_future_is_incomplete
2,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailed_Test:should_fail_if_completable_future_is_incomplete
0,29,org.assertj.core.util.Throwables_getRootCause_Test:should_return_null_if_throwable_has_no_cause
1,29,org.assertj.core.util.Throwables_getRootCause_Test:should_return_null_if_throwable_has_no_cause
2,29,org.assertj.core.util.Throwables_getRootCause_Test:should_return_null_if_throwable_has_no_cause
0,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_if_completable_future_was_cancelled
1,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_if_completable_future_was_cancelled
2,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_if_completable_future_was_cancelled
0,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_when_completable_future_is_null
1,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_when_completable_future_is_null
2,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_when_completable_future_is_null
0,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_if_completable_future_is_completed
1,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_if_completable_future_is_completed
2,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_if_completable_future_is_completed
0,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_if_completable_future_has_failed_with_wrong_throwable
1,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_if_completable_future_has_failed_with_wrong_throwable
2,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_if_completable_future_has_failed_with_wrong_throwable
0,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_if_completable_future_is_incomplete
1,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_if_completable_future_is_incomplete
2,29,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_if_completable_future_is_incomplete
0,29,org.assertj.core.internal.bytearrays.ByteArrays_assertContainsOnlyOnce_with_Integer_Arguments_Test:should_pass_if_actual_contains_given_values_only_even_if_duplicated
1,29,org.assertj.core.internal.bytearrays.ByteArrays_assertContainsOnlyOnce_with_Integer_Arguments_Test:should_pass_if_actual_contains_given_values_only_even_if_duplicated
2,29,org.assertj.core.internal.bytearrays.ByteArrays_assertContainsOnlyOnce_with_Integer_Arguments_Test:should_pass_if_actual_contains_given_values_only_even_if_duplicated
